# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120, verbose_name=b'name')),
                ('file', models.FileField(upload_to=b'mb/%Y/%m', verbose_name=b'file')),
                ('type', models.CharField(choices=[(b'img', b'Image'), (b'doc', b'Document')], max_length=16, verbose_name=b'type')),
                ('ext', models.CharField(max_length=40, verbose_name=b'type')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name=b'uploaded on')),
                ('uploaded_by', models.CharField(blank=True, max_length=80, verbose_name=b'uploaded by')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'height')),
            ],
        ),
    ]
